"""
AgentShield — Security scanning inspired by ECC's AgentShield.

Categories (30+ key rules):
- Secrets detection: API keys, tokens, passwords
- Permission auditing: excessive permissions
- MCP server risk: untrusted servers, excessive scopes
- Agent config review: dangerous tool access
- Hook injection: malicious patterns
- Dependency vulnerabilities: known CVEs

Output: A-F grade, JSON report, Markdown report
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Set, Any
from enum import Enum
import re
import logging
import os
import time
import json
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)


class Severity(Enum):
    """Severity levels for security findings."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class Grade(Enum):
    """Letter grade derived from the security score."""

    A = "A"  # 90-100
    B = "B"  # 80-89
    C = "C"  # 70-79
    D = "D"  # 60-69
    F = "F"  # <60


@dataclass
class SecurityFinding:
    """A single security issue found during scanning."""

    rule_id: str
    category: str
    severity: Severity
    message: str
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    snippet: Optional[str] = None
    remediation: str = ""


@dataclass
class SecurityReport:
    """Aggregated results from a security scan."""

    grade: Grade = Grade.F
    score: int = 0
    findings: List[SecurityFinding] = field(default_factory=list)
    summary: Dict[str, int] = field(default_factory=dict)
    scanned_files: int = 0
    scan_duration_ms: int = 0
    scan_timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    rules_triggered: Set[str] = field(default_factory=set)

    def to_markdown(self) -> str:
        """Generate a human-readable Markdown report."""
        lines: List[str] = [
            "# AgentShield Security Report",
            "",
            f"**Scan Date:** {self.scan_timestamp}",
            f"**Grade:** {self.grade.value} (Score: {self.score}/100)",
            f"**Files Scanned:** {self.scanned_files}",
            f"**Scan Duration:** {self.scan_duration_ms}ms",
            f"**Total Findings:** {len(self.findings)}",
            "",
            "## Severity Breakdown",
            "",
        ]
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = self.summary.get(sev, 0)
            emoji = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "🔵"}.get(
                sev, "⚪"
            )
            lines.append(f"- {emoji} **{sev.upper()}:** {count}")

        lines.extend(["", "## Findings", ""])

        if not self.findings:
            lines.append("✅ No security issues found!")
        else:
            for i, f in enumerate(self.findings, 1):
                severity_emoji = {
                    Severity.CRITICAL: "🔴",
                    Severity.HIGH: "🟠",
                    Severity.MEDIUM: "🟡",
                    Severity.LOW: "🟢",
                    Severity.INFO: "🔵",
                }.get(f.severity, "⚪")
                lines.extend(
                    [
                        f"### {i}. {f.rule_id} — {f.message}",
                        "",
                        f"- **Severity:** {severity_emoji} {f.severity.value.upper()}",
                        f"- **Category:** {f.category}",
                    ]
                )
                if f.file_path:
                    lines.append(f"- **File:** `{f.file_path}`")
                if f.line_number:
                    lines.append(f"- **Line:** {f.line_number}")
                if f.snippet:
                    lines.extend(["- **Snippet:**", f"  ```", f"  {f.snippet}", f"  ```"])
                lines.extend([f"- **Remediation:** {f.remediation}", ""])

        lines.extend(["---", "*Generated by AgentShield v1.0*"])
        return "\n".join(lines)

    def to_json(self) -> Dict[str, Any]:
        """Generate a JSON-serialisable dict for CI pipeline integration."""
        return {
            "grade": self.grade.value,
            "score": self.score,
            "scanned_files": self.scanned_files,
            "scan_duration_ms": self.scan_duration_ms,
            "scan_timestamp": self.scan_timestamp,
            "summary": self.summary,
            "rules_triggered": sorted(self.rules_triggered),
            "findings": [
                {
                    "rule_id": f.rule_id,
                    "category": f.category,
                    "severity": f.severity.value,
                    "message": f.message,
                    "file_path": f.file_path,
                    "line_number": f.line_number,
                    "snippet": f.snippet,
                    "remediation": f.remediation,
                }
                for f in self.findings
            ],
        }


@dataclass
class SecurityRule:
    """A single detection rule."""

    id: str
    category: str
    severity: Severity
    pattern: str
    description: str
    remediation: str
    applies_to: List[str]


class AgentShield:
    """Security scanner for agent configurations, code, and MCP connections.

    Performs static analysis on Python/JS/JSON/YAML files looking for secrets,
    injection vulnerabilities, permission issues, and MCP misconfigurations.
    """

    # ─── 35 security rules across 6 categories ────────────────────────
    RULES: List[SecurityRule] = [
        # ═══════════════════════════════════════════════════════════════
        # 1. SECRETS DETECTION (SEC-001 → SEC-009)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-001",
            "secrets",
            Severity.CRITICAL,
            r"sk-[a-zA-Z0-9]{48}",
            "Hardcoded OpenAI API key detected",
            "Store API keys in environment variables or a secret vault (e.g., Vault, AWS Secrets Manager)",
            [".py", ".ts", ".js", ".json", ".env", ".yaml", ".yml", ".toml"],
        ),
        SecurityRule(
            "SEC-002",
            "secrets",
            Severity.CRITICAL,
            r"ghp_[a-zA-Z0-9]{36}",
            "Hardcoded GitHub personal access token detected",
            "Use environment variables or GitHub App authentication",
            [".py", ".ts", ".js", ".json", ".env", ".yaml", ".yml"],
        ),
        SecurityRule(
            "SEC-003",
            "secrets",
            Severity.CRITICAL,
            r"AKIA[0-9A-Z]{16}",
            "Hardcoded AWS access key ID detected",
            "Use IAM roles, instance profiles, or AWS Secrets Manager",
            [".py", ".ts", ".js", ".json", ".env", ".yaml", ".yml"],
        ),
        SecurityRule(
            "SEC-004",
            "secrets",
            Severity.HIGH,
            r"password\s*=\s*[\"'][^\"']+[\"']",
            "Hardcoded password detected",
            "Use a secret management system or environment variables",
            [".py", ".ts", ".js", ".yaml", ".yml", ".env"],
        ),
        SecurityRule(
            "SEC-005",
            "secrets",
            Severity.HIGH,
            r"private[_-]?key\s*[=:]\s*[\"'][^\"']+[\"']",
            "Private key reference detected in code",
            "Store keys in a secure vault; never commit to version control",
            [".py", ".ts", ".js", ".pem", ".key", ".env"],
        ),
        SecurityRule(
            "SEC-006",
            "secrets",
            Severity.CRITICAL,
            r"xox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24}",
            "Hardcoded Slack token detected",
            "Use environment variables or Slack's OAuth 2.0 flow",
            [".py", ".ts", ".js", ".json", ".env"],
        ),
        SecurityRule(
            "SEC-007",
            "secrets",
            Severity.CRITICAL,
            r"eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*",
            "Hardcoded JWT token detected",
            "JWTs should be generated at runtime, never hardcoded",
            [".py", ".ts", ".js", ".json", ".env"],
        ),
        SecurityRule(
            "SEC-008",
            "secrets",
            Severity.HIGH,
            r"api[_-]?key\s*[=:]\s*[\"'][^\"']{16,}[\"']",
            "Generic API key pattern detected",
            "Store API keys in environment variables",
            [".py", ".ts", ".js", ".json", ".yaml", ".yml", ".env"],
        ),
        SecurityRule(
            "SEC-009",
            "secrets",
            Severity.HIGH,
            r"SG\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9_-]{43}",
            "Hardcoded SendGrid API key detected",
            "Use environment variables for SendGrid credentials",
            [".py", ".ts", ".js", ".json", ".env"],
        ),
        # ═══════════════════════════════════════════════════════════════
        # 2. PERMISSION ISSUES (SEC-010 → SEC-014)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-010",
            "permissions",
            Severity.HIGH,
            r"chmod\s+777",
            "Overly permissive file permissions (777)",
            "Use least-privilege permissions (e.g., 644 or 755)",
            [".py", ".sh", ".bash"],
        ),
        SecurityRule(
            "SEC-011",
            "permissions",
            Severity.MEDIUM,
            r"sudo\s+[a-zA-Z]",
            "Use of sudo without user restriction detected",
            "Avoid sudo in scripts; use capability-based access control",
            [".py", ".sh", ".bash"],
        ),
        SecurityRule(
            "SEC-012",
            "permissions",
            Severity.HIGH,
            r"os\.chmod\(.*0o777",
            "Python code setting 777 permissions",
            "Use os.chmod(path, 0o644) or more restrictive modes",
            [".py"],
        ),
        SecurityRule(
            "SEC-013",
            "permissions",
            Severity.MEDIUM,
            r"chown\s+root:root",
            "Changing file ownership to root",
            "Avoid running services as root; use dedicated service accounts",
            [".py", ".sh", ".bash"],
        ),
        SecurityRule(
            "SEC-014",
            "permissions",
            Severity.LOW,
            r"umask\s+0",
            "Overly permissive umask (0)",
            "Set umask to 0o022 or 0o027 for production",
            [".py", ".sh", ".bash"],
        ),
        # ═══════════════════════════════════════════════════════════════
        # 3. MCP SERVER RISKS (SEC-020 → SEC-025)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-020",
            "mcp_risk",
            Severity.HIGH,
            r"http://(?!localhost|127\.0\.0\.1|0\.0\.0\.0)",
            "Unencrypted MCP server URL (HTTP instead of HTTPS)",
            "Use HTTPS for all MCP server connections",
            [".py", ".json", ".yaml", ".yml", ".env"],
        ),
        SecurityRule(
            "SEC-021",
            "mcp_risk",
            Severity.MEDIUM,
            r"localhost:\d{4,5}",
            "MCP server on non-standard port",
            "Verify the port is intentional and properly secured",
            [".py", ".json", ".yaml", ".yml", ".env"],
        ),
        SecurityRule(
            "SEC-022",
            "mcp_risk",
            Severity.HIGH,
            r"\"scopes\"\s*:\s*\[\s*\"\*\"\s*\]",
            "MCP server configured with wildcard scopes",
            "Use minimal required scopes; avoid wildcard permissions",
            [".py", ".json", ".yaml", ".yml"],
        ),
        SecurityRule(
            "SEC-023",
            "mcp_risk",
            Severity.MEDIUM,
            r"verify_ssl\s*=\s*False",
            "SSL verification disabled for MCP connection",
            "Always verify SSL certificates in production",
            [".py"],
        ),
        SecurityRule(
            "SEC-024",
            "mcp_risk",
            Severity.MEDIUM,
            r"trust_env\s*=\s*True",
            "Trusting environment proxies for MCP connections",
            "Explicitly configure proxy settings instead of trusting env",
            [".py"],
        ),
        SecurityRule(
            "SEC-025",
            "mcp_risk",
            Severity.LOW,
            r"mcp.*\.onion",
            "MCP server on Tor onion domain",
            "Verify onion service is from a trusted source",
            [".py", ".json", ".yaml", ".yml", ".env"],
        ),
        # ═══════════════════════════════════════════════════════════════
        # 4. CODE INJECTION (SEC-030 → SEC-039)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-030",
            "injection",
            Severity.CRITICAL,
            r"\beval\s*\(",
            "Dangerous eval() usage detected",
            "Use ast.literal_eval(), json.loads(), or a safe parser",
            [".py"],
        ),
        SecurityRule(
            "SEC-031",
            "injection",
            Severity.CRITICAL,
            r"\bexec\s*\(",
            "Dangerous exec() usage detected",
            "Avoid dynamic code execution; use safer alternatives",
            [".py"],
        ),
        SecurityRule(
            "SEC-032",
            "injection",
            Severity.HIGH,
            r"subprocess\.call\s*\(.*shell\s*=\s*True",
            "Shell=True in subprocess call",
            "Use shell=False with a command list to prevent injection",
            [".py"],
        ),
        SecurityRule(
            "SEC-033",
            "injection",
            Severity.HIGH,
            r"subprocess\.Popen\s*\(.*shell\s*=\s*True",
            "Shell=True in subprocess.Popen",
            "Use shell=False with a command list to prevent injection",
            [".py"],
        ),
        SecurityRule(
            "SEC-034",
            "injection",
            Severity.HIGH,
            r"os\.system\s*\(",
            "os.system() call detected",
            "Use subprocess.run() with shell=False instead",
            [".py"],
        ),
        SecurityRule(
            "SEC-035",
            "injection",
            Severity.HIGH,
            r"\.format\s*\([^)]*\{[^}]*\}",
            "Potential format string injection",
            "Use f-strings or parameterized queries instead of .format()",
            [".py"],
        ),
        SecurityRule(
            "SEC-036",
            "injection",
            Severity.CRITICAL,
            r"pickle\.(loads|load)\s*\(",
            "Insecure deserialization with pickle",
            "Use json or a safe serialization format; pickle can execute arbitrary code",
            [".py"],
        ),
        SecurityRule(
            "SEC-037",
            "injection",
            Severity.CRITICAL,
            r"yaml\.load\s*\([^)]*\)(?!.*Loader\s*=\s*(SafeLoader|CSafeLoader))",
            "Unsafe YAML loading (yaml.load without SafeLoader)",
            "Use yaml.safe_load() or yaml.load(..., Loader=yaml.SafeLoader)",
            [".py"],
        ),
        SecurityRule(
            "SEC-038",
            "injection",
            Severity.HIGH,
            r"\binput\s*\(",
            "Untrusted user input via input()",
            "Validate and sanitize all user inputs; use argparse for CLI",
            [".py"],
        ),
        SecurityRule(
            "SEC-039",
            "injection",
            Severity.MEDIUM,
            r"__import__\s*\(",
            "Dynamic import detected",
            "Use standard imports; dynamic imports can bypass security controls",
            [".py"],
        ),
        # ═══════════════════════════════════════════════════════════════
        # 5. CRYPTOGRAPHY & SECURITY (SEC-040 → SEC-046)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-040",
            "crypto",
            Severity.CRITICAL,
            r"md5\s*\(",
            "Weak MD5 hash usage",
            "Use SHA-256 or stronger hashing algorithms",
            [".py"],
        ),
        SecurityRule(
            "SEC-041",
            "crypto",
            Severity.CRITICAL,
            r"sha1\s*\(",
            "Weak SHA-1 hash usage",
            "Use SHA-256 or stronger hashing algorithms",
            [".py"],
        ),
        SecurityRule(
            "SEC-042",
            "crypto",
            Severity.HIGH,
            r"random\.(random|randint|choice)",
            "Insecure random number generation",
            "Use secrets module for cryptographic randomness",
            [".py"],
        ),
        SecurityRule(
            "SEC-043",
            "crypto",
            Severity.HIGH,
            r"ssl\.(_create_unverified_context|CERT_NONE|CERT_OPTIONAL)",
            "Insecure SSL/TLS configuration",
            "Use ssl.create_default_context() with proper certificate verification",
            [".py"],
        ),
        SecurityRule(
            "SEC-044",
            "crypto",
            Severity.MEDIUM,
            r"DEBUG\s*=\s*True",
            "Debug mode enabled",
            "Set DEBUG=False in production environments",
            [".py", ".env", ".cfg"],
        ),
        SecurityRule(
            "SEC-045",
            "crypto",
            Severity.MEDIUM,
            r"TODO.*(security|fix|hack|bypass|workaround)",
            "Security-related TODO comment found",
            "Review and resolve all security TODOs before deployment",
            [".py", ".ts", ".js", ".md"],
        ),
        SecurityRule(
            "SEC-046",
            "crypto",
            Severity.HIGH,
            r"flask\.run\(.*debug\s*=\s*True",
            "Flask debug mode enabled",
            "Never run Flask with debug=True in production",
            [".py"],
        ),
        # ═══════════════════════════════════════════════════════════════
        # 6. NETWORK & SSRF (SEC-050 → SEC-056)
        # ═══════════════════════════════════════════════════════════════
        SecurityRule(
            "SEC-050",
            "network",
            Severity.HIGH,
            r"requests\.(get|post)\s*\(\s*(?!.*https://)[^)]+",
            "HTTP request without HTTPS",
            "Always use HTTPS for outbound requests",
            [".py"],
        ),
        SecurityRule(
            "SEC-051",
            "network",
            Severity.MEDIUM,
            r"urllib\.request\.urlopen\s*\(",
            "urlopen without proper validation",
            "Use requests library with timeout and SSL verification",
            [".py"],
        ),
        SecurityRule(
            "SEC-052",
            "network",
            Severity.MEDIUM,
            r"ftplib\.",
            "FTP connection detected (unencrypted)",
            "Use SFTP or FTPS for encrypted file transfers",
            [".py"],
        ),
        SecurityRule(
            "SEC-053",
            "network",
            Severity.HIGH,
            r"telnetlib\.",
            "Telnet connection detected (unencrypted)",
            "Use SSH instead of Telnet for remote access",
            [".py"],
        ),
        SecurityRule(
            "SEC-054",
            "network",
            Severity.LOW,
            r"smtp\.(SMTP|SMTP_SSL)\s*\(",
            "SMTP connection without explicit TLS",
            "Use SMTP_SSL or starttls() for encrypted email",
            [".py"],
        ),
        SecurityRule(
            "SEC-055",
            "network",
            Severity.MEDIUM,
            r"socket\.(socket|create_connection)",
            "Raw socket usage detected",
            "Use higher-level libraries with built-in security",
            [".py"],
        ),
        SecurityRule(
            "SEC-056",
            "network",
            Severity.LOW,
            r"\.listen\s*\(\s*\d+\s*\)(?!.*localhost)(?!.*127\.0\.0\.1)",
            "Network listener bound to all interfaces",
            "Bind to 127.0.0.1 or a specific interface",
            [".py"],
        ),
    ]

    # ─── Score deduction map ──────────────────────────────────────────
    DEDUCTIONS: Dict[Severity, int] = {
        Severity.CRITICAL: 10,
        Severity.HIGH: 5,
        Severity.MEDIUM: 3,
        Severity.LOW: 1,
        Severity.INFO: 0,
    }

    def __init__(self) -> None:
        self.findings: List[SecurityFinding] = []
        self._rules_triggered: Set[str] = set()

    # ------------------------------------------------------------------ #
    # Scanning
    # ------------------------------------------------------------------ #

    def scan_file(self, file_path: str) -> List[SecurityFinding]:
        """Scan a single file for security issues.

        Args:
            file_path: Path to the file to scan.

        Returns:
            List of :class:`SecurityFinding` objects.
        """
        findings: List[SecurityFinding] = []
        path = Path(file_path)

        if not path.is_file():
            logger.warning("File not found: %s", file_path)
            return findings

        ext = path.suffix.lower()
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except Exception as exc:
            logger.error("Cannot read %s: %s", file_path, exc)
            return findings

        lines = content.splitlines()

        for rule in self.RULES:
            if ext not in rule.applies_to:
                continue

            for line_idx, line in enumerate(lines, start=1):
                for match in re.finditer(rule.pattern, line):
                    finding = SecurityFinding(
                        rule_id=rule.id,
                        category=rule.category,
                        severity=rule.severity,
                        message=rule.description,
                        file_path=str(path.resolve()),
                        line_number=line_idx,
                        snippet=line.strip()[:200],
                        remediation=rule.remediation,
                    )
                    findings.append(finding)
                    self._rules_triggered.add(rule.id)
                    logger.debug(
                        "[%s] %s at %s:%d", rule.id, rule.description, file_path, line_idx
                    )

        self.findings.extend(findings)
        return findings

    def scan_directory(
        self, dir_path: str, extensions: Optional[List[str]] = None
    ) -> SecurityReport:
        """Scan an entire directory for security issues.

        Args:
            dir_path: Root directory to scan.
            extensions: If given, only scan files with these extensions.

        Returns:
            A :class:`SecurityReport` summarising all findings.
        """
        start_time = time.time() * 1000
        root = Path(dir_path)

        if not root.is_dir():
            raise ValueError(f"Not a directory: {dir_path}")

        target_exts = set(extensions) if extensions else None
        files_scanned = 0
        all_findings: List[SecurityFinding] = []

        for file_path in root.rglob("*"):
            if not file_path.is_file():
                continue
            if file_path.name.startswith("."):
                continue  # skip hidden files

            ext = file_path.suffix.lower()
            if target_exts and ext not in target_exts:
                continue

            # Skip common non-source directories
            parts = set(file_path.parts)
            if parts & {"node_modules", ".git", "__pycache__", ".venv", "venv", "dist", "build"}:
                continue

            findings = self.scan_file(str(file_path))
            all_findings.extend(findings)
            files_scanned += 1

        duration_ms = int(time.time() * 1000 - start_time)
        return self._build_report(all_findings, files_scanned, duration_ms)

    def scan_config(self, config: Dict[str, Any]) -> List[SecurityFinding]:
        """Scan an agent or application configuration dictionary.

        Args:
            config: Configuration dict (e.g., from a JSON/YAML file).

        Returns:
            List of :class:`SecurityFinding` objects.
        """
        findings: List[SecurityFinding] = []
        config_str = json.dumps(config, indent=2, default=str)
        lines = config_str.splitlines()

        for rule in self.RULES:
            for line_idx, line in enumerate(lines, start=1):
                for match in re.finditer(rule.pattern, line):
                    finding = SecurityFinding(
                        rule_id=rule.id,
                        category=rule.category,
                        severity=rule.severity,
                        message=rule.description,
                        file_path="<config>",
                        line_number=line_idx,
                        snippet=line.strip()[:200],
                        remediation=rule.remediation,
                    )
                    findings.append(finding)
                    self._rules_triggered.add(rule.id)

        self.findings.extend(findings)
        return findings

    def scan_mcp_config(self, mcp_config: Dict[str, Any]) -> List[SecurityFinding]:
        """Scan an MCP server configuration for risks.

        Args:
            mcp_config: MCP configuration dict.

        Returns:
            List of :class:`SecurityFinding` objects.
        """
        findings: List[SecurityFinding] = []

        servers = mcp_config.get("servers", mcp_config.get("mcpServers", {}))
        if isinstance(servers, dict):
            for name, server_conf in servers.items():
                # Check for HTTP URLs
                url = server_conf.get("url", "")
                if url.startswith("http://") and not any(
                    h in url for h in ("localhost", "127.0.0.1", "0.0.0.0")
                ):
                    findings.append(
                        SecurityFinding(
                            rule_id="MCP-001",
                            category="mcp_risk",
                            severity=Severity.HIGH,
                            message=f"MCP server '{name}' uses unencrypted HTTP",
                            file_path="<mcp_config>",
                            snippet=f"url: {url}",
                            remediation="Use HTTPS for all MCP server connections",
                        )
                    )

                # Check for wildcard scopes
                scopes = server_conf.get("scopes", [])
                if "*" in scopes:
                    findings.append(
                        SecurityFinding(
                            rule_id="MCP-002",
                            category="mcp_risk",
                            severity=Severity.HIGH,
                            message=f"MCP server '{name}' has wildcard scopes",
                            file_path="<mcp_config>",
                            snippet=f"scopes: {scopes}",
                            remediation="Use minimal required scopes",
                        )
                    )

                # Check for disabled SSL verification
                if server_conf.get("verify_ssl") is False:
                    findings.append(
                        SecurityFinding(
                            rule_id="MCP-003",
                            category="mcp_risk",
                            severity=Severity.MEDIUM,
                            message=f"MCP server '{name}' has SSL verification disabled",
                            file_path="<mcp_config>",
                            snippet="verify_ssl: false",
                            remediation="Always verify SSL certificates in production",
                        )
                    )

                # Check for auth token in config
                if server_conf.get("auth_token") and not server_conf.get("auth_token", "").startswith(
                    "${"
                ):
                    findings.append(
                        SecurityFinding(
                            rule_id="MCP-004",
                            category="secrets",
                            severity=Severity.CRITICAL,
                            message=f"Hardcoded auth token for MCP server '{name}'",
                            file_path="<mcp_config>",
                            snippet=f"auth_token: {'*' * 10}",
                            remediation="Use environment variable references for auth tokens",
                        )
                    )

        self.findings.extend(findings)
        return findings

    # ------------------------------------------------------------------ #
    # Auto-fix
    # ------------------------------------------------------------------ #

    def auto_fix(self, report: SecurityReport) -> Dict[str, str]:
        """Apply safe automatic fixes for findings where possible.

        Currently supports:
        - Replacing ``yaml.load()`` → ``yaml.safe_load()``
        - Replacing ``eval()`` → ``ast.literal_eval()``
        - Replacing ``os.system()`` → ``subprocess.run()``
        - Setting ``DEBUG = False``

        Args:
            report: The security report to fix.

        Returns:
            Mapping of finding index → fix description.
        """
        fixes: Dict[str, str] = {}

        for i, finding in enumerate(report.findings):
            key = str(i)
            if finding.rule_id == "SEC-037":
                fixes[key] = "Replace yaml.load() with yaml.safe_load()"
            elif finding.rule_id == "SEC-030":
                fixes[key] = "Replace eval() with ast.literal_eval() or json.loads()"
            elif finding.rule_id == "SEC-034":
                fixes[key] = "Replace os.system() with subprocess.run(..., shell=False)"
            elif finding.rule_id == "SEC-044":
                fixes[key] = "Set DEBUG = False in production"
            elif finding.rule_id == "SEC-046":
                fixes[key] = "Set debug=False in Flask app.run()"
            elif finding.rule_id == "SEC-042":
                fixes[key] = "Replace random with secrets module for crypto operations"
            elif finding.rule_id == "SEC-040" or finding.rule_id == "SEC-041":
                fixes[key] = "Replace MD5/SHA1 with hashlib.sha256()"
            elif finding.rule_id == "SEC-032" or finding.rule_id == "SEC-033":
                fixes[key] = "Set shell=False and pass command as a list"
            elif finding.rule_id == "SEC-024":
                fixes[key] = "Set trust_env=False or configure proxies explicitly"
            elif finding.rule_id == "SEC-023":
                fixes[key] = "Remove verify_ssl=False; use proper certificates"

        return fixes

    # ------------------------------------------------------------------ #
    # Report generation
    # ------------------------------------------------------------------ #

    def generate_report(self) -> SecurityReport:
        """Generate a report from all findings collected so far."""
        return self._build_report(self.findings, 0, 0)

    def _build_report(
        self, findings: List[SecurityFinding], scanned_files: int, duration_ms: int
    ) -> SecurityReport:
        """Compute grade and summary from findings."""
        summary: Dict[str, int] = {
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0,
        }

        score = 100
        for f in findings:
            sev_key = f.severity.value
            summary[sev_key] = summary.get(sev_key, 0) + 1
            deduction = self.DEDUCTIONS.get(f.severity, 0)
            score -= deduction

        score = max(0, score)
        grade = self._score_to_grade(score)

        return SecurityReport(
            grade=grade,
            score=score,
            findings=findings,
            summary=summary,
            scanned_files=scanned_files,
            scan_duration_ms=duration_ms,
            rules_triggered=self._rules_triggered,
        )

    @staticmethod
    def _score_to_grade(score: int) -> Grade:
        if score >= 90:
            return Grade.A
        elif score >= 80:
            return Grade.B
        elif score >= 70:
            return Grade.C
        elif score >= 60:
            return Grade.D
        return Grade.F

    def clear_findings(self) -> None:
        """Clear all collected findings."""
        self.findings.clear()
        self._rules_triggered.clear()

    def add_custom_rule(self, rule: SecurityRule) -> None:
        """Add a user-defined security rule.

        Args:
            rule: The :class:`SecurityRule` to add.
        """
        self.RULES.append(rule)
        logger.info("Added custom security rule: %s (%s)", rule.id, rule.description)

    # ------------------------------------------------------------------ #
    # Dunder helpers
    # ------------------------------------------------------------------ #

    def __repr__(self) -> str:
        return f"<AgentShield rules={len(self.RULES)} findings={len(self.findings)}>"


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

def quick_scan_file(file_path: str) -> SecurityReport:
    """One-shot scan a single file and return a report."""
    shield = AgentShield()
    start = time.time() * 1000
    shield.scan_file(file_path)
    duration = int(time.time() * 1000 - start)
    report = shield.generate_report()
    report.scanned_files = 1
    report.scan_duration_ms = duration
    return report


def quick_scan_directory(dir_path: str, extensions: Optional[List[str]] = None) -> SecurityReport:
    """One-shot scan a directory and return a report."""
    shield = AgentShield()
    return shield.scan_directory(dir_path, extensions)
