"""
Quality Verifier — Continuous verification system.

Runs: code tests, security scan, lint, type check, coverage, performance.
Must pass before any commit or deployment.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Callable
from enum import Enum
import logging
import time
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger(__name__)


class Status(Enum):
    """Status of an individual verification check."""

    PASS = "pass"
    FAIL = "fail"
    SKIP = "skip"
    ERROR = "error"


@dataclass
class VerificationResult:
    """Result of a single verification check."""

    name: str
    status: Status
    score: float  # 0.0 – 100.0
    message: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    duration_ms: int = 0

    @property
    def passed(self) -> bool:
        return self.status == Status.PASS


@dataclass
class SecurityResult:
    """Result of a security scan verification."""

    status: Status
    score: float
    grade: str
    findings_count: int
    critical_count: int
    high_count: int
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PerformanceResult:
    """Result of a performance benchmark verification."""

    status: Status
    score: float
    execution_time_ms: float
    memory_usage_mb: float
    throughput: float  # ops/sec
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CoverageResult:
    """Result of a code coverage verification."""

    status: Status
    score: float  # coverage percentage
    line_coverage: float
    branch_coverage: float
    total_lines: int
    covered_lines: int
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LintResult:
    """Result of a linting verification."""

    status: Status
    score: float
    errors: int
    warnings: int
    style_issues: int
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TypeResult:
    """Result of a type-checking verification."""

    status: Status
    score: float
    type_errors: int
    missing_annotations: int
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GateResult:
    """Aggregated quality gate result."""

    passed: bool
    overall_score: float
    threshold_results: Dict[str, VerificationResult] = field(default_factory=dict)
    summary: Dict[str, int] = field(default_factory=dict)
    duration_ms: int = 0
    timestamp: str = field(default_factory=lambda: time.strftime("%Y-%m-%dT%H:%M:%SZ"))

    def to_markdown(self) -> str:
        """Generate a human-readable Markdown summary."""
        emoji = "✅" if self.passed else "❌"
        lines: List[str] = [
            f"# {emoji} Quality Gate Result",
            "",
            f"**Overall Score:** {self.overall_score:.1f}/100",
            f"**Status:** {'PASSED' if self.passed else 'FAILED'}",
            f"**Duration:** {self.duration_ms}ms",
            f"**Timestamp:** {self.timestamp}",
            "",
            "## Threshold Results",
            "",
        ]
        for name, result in self.threshold_results.items():
            status_emoji = {
                Status.PASS: "✅",
                Status.FAIL: "❌",
                Status.SKIP: "⏭️",
                Status.ERROR: "⚠️",
            }.get(result.status, "❓")
            lines.append(
                f"- {status_emoji} **{name}**: {result.status.value.upper()} "
                f"(score: {result.score:.1f}) — {result.message}"
            )
        lines.extend(["", "---", "*Generated by QualityVerifier*"])
        return "\n".join(lines)

    def to_json(self) -> Dict[str, Any]:
        """Generate a JSON-serialisable dict."""
        return {
            "passed": self.passed,
            "overall_score": self.overall_score,
            "duration_ms": self.duration_ms,
            "timestamp": self.timestamp,
            "threshold_results": {
                name: {
                    "name": r.name,
                    "status": r.status.value,
                    "score": r.score,
                    "message": r.message,
                    "duration_ms": r.duration_ms,
                }
                for name, r in self.threshold_results.items()
            },
            "summary": self.summary,
        }


class QualityVerifier:
    """Continuous verification system for code quality gates.

    Runs all checks required before a commit or deployment:
    unit tests, security scan, lint, type check, coverage, performance benchmarks.

    Args:
        thresholds: Dict of check name → minimum required score.
            Defaults enforce production-grade standards.
    """

    DEFAULT_THRESHOLDS: Dict[str, float] = {
        "tests": 80.0,  # min test pass rate
        "security": 80.0,  # min security score (A=90, B=80, ...)
        "lint": 95.0,  # lint score (0 errors = 100)
        "types": 90.0,  # type check score
        "coverage": 80.0,  # min line coverage %
        "performance": 70.0,  # performance benchmark score
    }

    def __init__(self, thresholds: Optional[Dict[str, float]] = None) -> None:
        self.thresholds = {**self.DEFAULT_THRESHOLDS, **(thresholds or {})}
        self._results: Dict[str, VerificationResult] = {}

    # ------------------------------------------------------------------ #
    # Individual verification methods
    # ------------------------------------------------------------------ #

    def verify_code(self, file_path: str, tests: Optional[List[Callable[..., Any]]] = None) -> VerificationResult:
        """Verify code by running unit tests.

        Args:
            file_path: Path to the source file under test.
            tests: Optional list of test callables to run.

        Returns:
            :class:`VerificationResult` with test outcomes.
        """
        start = time.time() * 1000
        name = "tests"

        if tests is None:
            # Try to run pytest on the file
            result = self._run_pytest(file_path)
            duration = int(time.time() * 1000 - start)
            self._results[name] = result._replace(duration_ms=duration, name=name)
            return self._results[name]

        passed = 0
        failed = 0
        errors = 0
        for test in tests:
            try:
                test()
                passed += 1
            except AssertionError:
                failed += 1
            except Exception:
                errors += 1

        total = passed + failed + errors
        score = (passed / total * 100) if total > 0 else 0.0
        threshold = self.thresholds.get(name, 0.0)
        status = Status.PASS if score >= threshold else Status.FAIL

        result = VerificationResult(
            name=name,
            status=status,
            score=score,
            message=f"{passed}/{total} tests passed ({failed} failed, {errors} errors)",
            details={"passed": passed, "failed": failed, "errors": errors, "total": total},
            duration_ms=int(time.time() * 1000 - start),
        )
        self._results[name] = result
        return result

    def verify_security(
        self, code_path: str, shield: Optional[Any] = None
    ) -> SecurityResult:
        """Run AgentShield security scan on the codebase.

        Args:
            code_path: Path to the code directory or file.
            shield: Optional :class:`AgentShield` instance.

        Returns:
            :class:`SecurityResult` with security metrics.
        """
        start = time.time() * 1000

        try:
            from security.agentshield import AgentShield

            shield = shield or AgentShield()
            path = Path(code_path)

            if path.is_file():
                shield.scan_file(code_path)
            else:
                shield.scan_directory(code_path)

            report = shield.generate_report()
            score = report.score
            threshold = self.thresholds.get("security", 80.0)
            status = Status.PASS if score >= threshold else Status.FAIL

            result = SecurityResult(
                status=status,
                score=score,
                grade=report.grade.value,
                findings_count=len(report.findings),
                critical_count=report.summary.get("critical", 0),
                high_count=report.summary.get("high", 0),
                details=report.to_json(),
            )
        except Exception as exc:
            logger.error("Security verification failed: %s", exc)
            result = SecurityResult(
                status=Status.ERROR,
                score=0.0,
                grade="F",
                findings_count=0,
                critical_count=0,
                high_count=0,
                details={"error": str(exc)},
            )

        duration = int(time.time() * 1000 - start)
        self._results["security"] = VerificationResult(
            name="security",
            status=result.status,
            score=result.score,
            message=f"Grade {result.grade}: {result.findings_count} findings "
            f"({result.critical_count} critical, {result.high_count} high)",
            details=result.details,
            duration_ms=duration,
        )
        return result

    def verify_performance(
        self,
        code: Callable[..., Any],
        benchmark: Optional[Dict[str, Any]] = None,
        args: Optional[tuple] = None,
        kwargs: Optional[Dict[str, Any]] = None,
    ) -> PerformanceResult:
        """Verify performance by running a benchmark.

        Args:
            code: Callable to benchmark.
            benchmark: Optional benchmark config dict with ``max_time_ms``,
                ``max_memory_mb``, ``min_throughput``.
            args: Positional args for *code*.
            kwargs: Keyword args for *code*.

        Returns:
            :class:`PerformanceResult` with performance metrics.
        """
        start = time.time() * 1000
        benchmark = benchmark or {}
        args = args or ()
        kwargs = kwargs or {}

        max_time_ms = benchmark.get("max_time_ms", 5000)
        max_memory_mb = benchmark.get("max_memory_mb", 512)
        min_throughput = benchmark.get("min_throughput", 1.0)

        try:
            import tracemalloc

            tracemalloc.start()
            exec_start = time.time() * 1000
            result = code(*args, **kwargs)
            exec_time = time.time() * 1000 - exec_start
            _, peak = tracemalloc.get_traced_memory()
            tracemalloc.stop()
            memory_mb = peak / (1024 * 1024)

            throughput = 1.0 / (exec_time / 1000) if exec_time > 0 else float("inf")

            # Calculate score (0-100) based on thresholds
            time_score = max(0, 100 - (exec_time / max_time_ms * 100))
            mem_score = max(0, 100 - (memory_mb / max_memory_mb * 100))
            tput_score = 100 if throughput >= min_throughput else (throughput / min_throughput * 100)
            score = (time_score + mem_score + tput_score) / 3

            threshold = self.thresholds.get("performance", 70.0)
            status = Status.PASS if score >= threshold else Status.FAIL

            perf_result = PerformanceResult(
                status=status,
                score=score,
                execution_time_ms=exec_time,
                memory_usage_mb=memory_mb,
                throughput=throughput,
                details={"return_value": str(result)[:200]},
            )
        except Exception as exc:
            logger.error("Performance verification failed: %s", exc)
            perf_result = PerformanceResult(
                status=Status.ERROR,
                score=0.0,
                execution_time_ms=0.0,
                memory_usage_mb=0.0,
                throughput=0.0,
                details={"error": str(exc)},
            )

        duration = int(time.time() * 1000 - start)
        self._results["performance"] = VerificationResult(
            name="performance",
            status=perf_result.status,
            score=perf_result.score,
            message=f"{perf_result.execution_time_ms:.0f}ms, "
            f"{perf_result.memory_usage_mb:.1f}MB, "
            f"{perf_result.throughput:.1f} ops/sec",
            details=perf_result.details,
            duration_ms=duration,
        )
        return perf_result

    def verify_coverage(
        self, code_path: str, test_path: Optional[str] = None
    ) -> CoverageResult:
        """Verify code coverage using pytest-cov.

        Args:
            code_path: Path to source code.
            test_path: Path to test files.

        Returns:
            :class:`CoverageResult` with coverage metrics.
        """
        start = time.time() * 1000
        test_path = test_path or code_path

        try:
            result = subprocess.run(  # nosec: trusted command
                [
                    sys.executable,
                    "-m",
                    "pytest",
                    test_path,
                    f"--cov={code_path}",
                    "--cov-report=json",
                    "--cov-report=term-missing",
                    "-q",
                ],
                capture_output=True,
                text=True,
                timeout=120,
            )

            # Parse coverage from output
            coverage_pct = 0.0
            for line in result.stdout.splitlines():
                if "TOTAL" in line or "coverage" in line.lower():
                    parts = line.split()
                    for part in parts:
                        try:
                            if "%" in part:
                                coverage_pct = float(part.replace("%", ""))
                                break
                        except ValueError:
                            continue

            # Try to read coverage.json
            covered_lines = 0
            total_lines = 1
            try:
                cov_json = Path("coverage.json")
                if cov_json.exists():
                    import json

                    cov_data = json.loads(cov_json.read_text())
                    totals = cov_data.get("totals", {})
                    covered_lines = totals.get("covered_lines", 0)
                    total_lines = totals.get("num_statements", 1)
                    coverage_pct = (covered_lines / total_lines * 100) if total_lines > 0 else 0.0
            except Exception:
                pass

            threshold = self.thresholds.get("coverage", 80.0)
            status = Status.PASS if coverage_pct >= threshold else Status.FAIL

            cov_result = CoverageResult(
                status=status,
                score=coverage_pct,
                line_coverage=coverage_pct,
                branch_coverage=coverage_pct * 0.9,  # estimate
                total_lines=total_lines,
                covered_lines=covered_lines,
                details={"pytest_output": result.stdout[-2000:]},
            )
        except FileNotFoundError:
            logger.warning("pytest-cov not installed; skipping coverage")
            cov_result = CoverageResult(
                status=Status.SKIP,
                score=0.0,
                line_coverage=0.0,
                branch_coverage=0.0,
                total_lines=0,
                covered_lines=0,
                details={"reason": "pytest-cov not installed"},
            )
        except Exception as exc:
            logger.error("Coverage verification failed: %s", exc)
            cov_result = CoverageResult(
                status=Status.ERROR,
                score=0.0,
                line_coverage=0.0,
                branch_coverage=0.0,
                total_lines=0,
                covered_lines=0,
                details={"error": str(exc)},
            )

        duration = int(time.time() * 1000 - start)
        self._results["coverage"] = VerificationResult(
            name="coverage",
            status=cov_result.status,
            score=cov_result.score,
            message=f"{cov_result.score:.1f}% line coverage "
            f"({cov_result.covered_lines}/{cov_result.total_lines} lines)",
            details=cov_result.details,
            duration_ms=duration,
        )
        return cov_result

    def verify_lint(self, code_path: str) -> LintResult:
        """Run lint checks (flake8, pylint, ruff) on the code.

        Args:
            code_path: Path to source file or directory.

        Returns:
            :class:`LintResult` with lint metrics.
        """
        start = time.time() * 1000
        errors = 0
        warnings = 0
        style = 0

        # Try ruff first (fastest), then flake8
        for tool, cmd in [
            ("ruff", [sys.executable, "-m", "ruff", "check", code_path]),
            ("flake8", [sys.executable, "-m", "flake8", "--count", code_path]),
        ]:
            try:
                result = subprocess.run(  # nosec: trusted linter commands
                    cmd, capture_output=True, text=True, timeout=60
                )
                output = result.stdout + result.stderr
                # Count issues from output
                errors += output.lower().count("error")
                warnings += output.lower().count("warning")
                style += len([l for l in output.splitlines() if l.strip() and not l.startswith("=")])
                logger.debug("%s found issues: %s", tool, output[:500])
                break  # ruff succeeded, skip flake8
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue

        # Score: 100 if 0 errors, drops with each error
        score = max(0, 100 - errors * 5 - warnings * 2 - style * 0.5)
        threshold = self.thresholds.get("lint", 95.0)
        status = Status.PASS if errors == 0 and score >= threshold else Status.FAIL

        lint_result = LintResult(
            status=status,
            score=score,
            errors=errors,
            warnings=warnings,
            style_issues=style,
            details={"tools_tried": ["ruff", "flake8"]},
        )

        duration = int(time.time() * 1000 - start)
        self._results["lint"] = VerificationResult(
            name="lint",
            status=lint_result.status,
            score=lint_result.score,
            message=f"{errors} errors, {warnings} warnings, {style} style issues",
            details=lint_result.details,
            duration_ms=duration,
        )
        return lint_result

    def verify_types(self, code_path: str) -> TypeResult:
        """Run type checking (mypy) on the code.

        Args:
            code_path: Path to source file or directory.

        Returns:
            :class:`TypeResult` with type-check metrics.
        """
        start = time.time() * 1000

        try:
            result = subprocess.run(  # nosec: trusted mypy command
                [
                    sys.executable,
                    "-m",
                    "mypy",
                    "--ignore-missing-imports",
                    "--show-error-codes",
                    "--pretty",
                    code_path,
                ],
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = result.stdout + result.stderr
            type_errors = len([l for l in output.splitlines() if ": error:" in l])
            missing_anno = len([l for l in output.splitlines() if "annotation" in l.lower()])

            # Score: 100 if 0 type errors
            score = max(0, 100 - type_errors * 3 - missing_anno * 1)
            threshold = self.thresholds.get("types", 90.0)
            status = Status.PASS if score >= threshold else Status.FAIL

            type_result = TypeResult(
                status=status,
                score=score,
                type_errors=type_errors,
                missing_annotations=missing_anno,
                details={"mypy_output": output[-2000:]},
            )
        except FileNotFoundError:
            logger.warning("mypy not installed; skipping type check")
            type_result = TypeResult(
                status=Status.SKIP,
                score=0.0,
                type_errors=0,
                missing_annotations=0,
                details={"reason": "mypy not installed"},
            )
        except Exception as exc:
            logger.error("Type verification failed: %s", exc)
            type_result = TypeResult(
                status=Status.ERROR,
                score=0.0,
                type_errors=0,
                missing_annotations=0,
                details={"error": str(exc)},
            )

        duration = int(time.time() * 1000 - start)
        self._results["types"] = VerificationResult(
            name="types",
            status=type_result.status,
            score=type_result.score,
            message=f"{type_result.type_errors} type errors, "
            f"{type_result.missing_annotations} missing annotations",
            details=type_result.details,
            duration_ms=duration,
        )
        return type_result

    # ------------------------------------------------------------------ #
    # Aggregate quality gate
    # ------------------------------------------------------------------ #

    def run_quality_gate(self, code_path: str, **kwargs: Any) -> GateResult:
        """Run ALL verification checks and produce a gate result.

        This is the main entry point — runs tests, security scan, lint,
        type check, coverage, and performance benchmarks.

        Args:
            code_path: Root path to the codebase.
            **kwargs: Additional arguments passed to individual checks.

        Returns:
            :class:`GateResult` with overall pass/fail status.
        """
        gate_start = time.time() * 1000
        self._results.clear()

        logger.info("Running quality gate on: %s", code_path)

        # 1. Security scan
        try:
            self.verify_security(code_path)
        except Exception as exc:
            logger.error("Security check failed: %s", exc)
            self._results["security"] = VerificationResult(
                name="security", status=Status.ERROR, score=0.0, message=str(exc)
            )

        # 2. Lint
        try:
            self.verify_lint(code_path)
        except Exception as exc:
            logger.error("Lint check failed: %s", exc)
            self._results["lint"] = VerificationResult(
                name="lint", status=Status.ERROR, score=0.0, message=str(exc)
            )

        # 3. Type check
        try:
            self.verify_types(code_path)
        except Exception as exc:
            logger.error("Type check failed: %s", exc)
            self._results["types"] = VerificationResult(
                name="types", status=Status.ERROR, score=0.0, message=str(exc)
            )

        # 4. Coverage
        try:
            self.verify_coverage(code_path, kwargs.get("test_path"))
        except Exception as exc:
            logger.error("Coverage check failed: %s", exc)
            self._results["coverage"] = VerificationResult(
                name="coverage", status=Status.ERROR, score=0.0, message=str(exc)
            )

        # 5. Code tests
        try:
            tests = kwargs.get("tests")
            if tests:
                self.verify_code(code_path, tests)
            else:
                self._results["tests"] = VerificationResult(
                    name="tests",
                    status=Status.SKIP,
                    score=0.0,
                    message="No tests provided — skipped",
                )
        except Exception as exc:
            logger.error("Test check failed: %s", exc)
            self._results["tests"] = VerificationResult(
                name="tests", status=Status.ERROR, score=0.0, message=str(exc)
            )

        # 6. Performance (if benchmark provided)
        benchmark = kwargs.get("benchmark")
        if benchmark:
            try:
                self.verify_performance(
                    benchmark["code"],
                    benchmark.get("config"),
                    benchmark.get("args"),
                    benchmark.get("kwargs"),
                )
            except Exception as exc:
                logger.error("Performance check failed: %s", exc)
                self._results["performance"] = VerificationResult(
                    name="performance", status=Status.ERROR, score=0.0, message=str(exc)
                )
        else:
            self._results["performance"] = VerificationResult(
                name="performance",
                status=Status.SKIP,
                score=0.0,
                message="No benchmark provided — skipped",
            )

        # ─── Aggregate ──────────────────────────────────────────────
        total_score = sum(r.score for r in self._results.values()) / max(
            len(self._results), 1
        )
        all_passed = all(r.status in (Status.PASS, Status.SKIP) for r in self._results.values())

        summary: Dict[str, int] = {
            "pass": sum(1 for r in self._results.values() if r.status == Status.PASS),
            "fail": sum(1 for r in self._results.values() if r.status == Status.FAIL),
            "skip": sum(1 for r in self._results.values() if r.status == Status.SKIP),
            "error": sum(1 for r in self._results.values() if r.status == Status.ERROR),
        }

        duration = int(time.time() * 1000 - gate_start)
        gate = GateResult(
            passed=all_passed,
            overall_score=total_score,
            threshold_results=dict(self._results),
            summary=summary,
            duration_ms=duration,
        )

        logger.info(
            "Quality gate %s — score: %.1f, %d passed, %d failed, %d skipped, %d errors",
            "PASSED" if all_passed else "FAILED",
            total_score,
            summary["pass"],
            summary["fail"],
            summary["skip"],
            summary["error"],
        )
        return gate

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def _run_pytest(self, file_path: str) -> VerificationResult:
        """Run pytest on a file and return a VerificationResult."""
        try:
            result = subprocess.run(  # nosec: trusted pytest command
                [sys.executable, "-m", "pytest", file_path, "-v", "--tb=short", "-q"],
                capture_output=True,
                text=True,
                timeout=120,
            )
            output = result.stdout + result.stderr
            passed = output.count(" PASSED")
            failed = output.count(" FAILED")
            errors = output.count(" ERROR")
            total = passed + failed + errors

            score = (passed / total * 100) if total > 0 else 0.0
            threshold = self.thresholds.get("tests", 80.0)
            status = Status.PASS if score >= threshold else Status.FAIL

            return VerificationResult(
                name="tests",
                status=status,
                score=score,
                message=f"{passed}/{total} tests passed ({failed} failed, {errors} errors)",
                details={"output": output[-2000:]},
                duration_ms=0,
            )
        except FileNotFoundError:
            return VerificationResult(
                name="tests",
                status=Status.SKIP,
                score=0.0,
                message="pytest not installed",
                details={},
                duration_ms=0,
            )
        except Exception as exc:
            return VerificationResult(
                name="tests",
                status=Status.ERROR,
                score=0.0,
                message=str(exc),
                details={},
                duration_ms=0,
            )

    def get_results(self) -> Dict[str, VerificationResult]:
        """Return all verification results collected so far."""
        return dict(self._results)

    def __repr__(self) -> str:
        passed = sum(1 for r in self._results.values() if r.status == Status.PASS)
        return f"<QualityVerifier checks={len(self._results)} passed={passed}>"
